createobject("wscript.shell").run "fds2ascii.exe",9
wscript.sleep 500
set ws=wscript.createobject("wscript.shell")
wscript.sleep 100
ws.sendkeys "NanyiFirev3"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "2"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "1"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "z"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "9 10 12"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "5"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "1"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "7"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "13"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "19"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "25"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "Floor1_9_10_Data.txt"
ws.sendkeys "{ENTER}"
wscript.sleep 500

createobject("wscript.shell").run "fds2ascii.exe",9
wscript.sleep 500
set ws=wscript.createobject("wscript.shell")
wscript.sleep 100
ws.sendkeys "NanyiFirev3"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "2"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "1"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "z"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "9 10 12"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "5"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "2"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "8"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "14"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "20"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "26"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "Floor2_9_10_Data.txt"
ws.sendkeys "{ENTER}"
wscript.sleep 500

createobject("wscript.shell").run "fds2ascii.exe",9
wscript.sleep 500
set ws=wscript.createobject("wscript.shell")
wscript.sleep 100
ws.sendkeys "NanyiFirev3"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "2"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "1"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "z"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "9 10 12"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "5"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "3"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "9"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "15"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "21"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "27"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "Floor3_9_10_Data.txt"
ws.sendkeys "{ENTER}"
wscript.sleep 500

createobject("wscript.shell").run "fds2ascii.exe",9
wscript.sleep 500
set ws=wscript.createobject("wscript.shell")
wscript.sleep 100
ws.sendkeys "NanyiFirev3"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "2"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "1"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "z"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "9 10 12"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "5"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "4"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "10"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "16"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "22"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "28"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "Floor4_9_10_Data.txt"
ws.sendkeys "{ENTER}"
wscript.sleep 500

createobject("wscript.shell").run "fds2ascii.exe",9
wscript.sleep 500
set ws=wscript.createobject("wscript.shell")
wscript.sleep 100
ws.sendkeys "NanyiFirev3"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "2"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "1"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "z"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "9 10 12"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "5"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "5"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "11"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "17"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "23"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "29"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "Floor5_9_10_Data.txt"
ws.sendkeys "{ENTER}"
wscript.sleep 500

createobject("wscript.shell").run "fds2ascii.exe",9
wscript.sleep 500
set ws=wscript.createobject("wscript.shell")
wscript.sleep 100
ws.sendkeys "NanyiFirev3"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "2"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "1"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "z"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "9 10 12"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "5"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "6"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "12"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "18"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "24"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "30"
ws.sendkeys "{ENTER}"
wscript.sleep 100
ws.sendkeys "Floor6_9_10_Data.txt"
ws.sendkeys "{ENTER}"
wscript.sleep 500

