package fire_db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import fire_db.GridInfo;
import fire_db.ZoneInfo;

import fire_db.GridInfoDao;
import fire_db.ZoneInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gridInfoDaoConfig;
    private final DaoConfig zoneInfoDaoConfig;

    private final GridInfoDao gridInfoDao;
    private final ZoneInfoDao zoneInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gridInfoDaoConfig = daoConfigMap.get(GridInfoDao.class).clone();
        gridInfoDaoConfig.initIdentityScope(type);

        zoneInfoDaoConfig = daoConfigMap.get(ZoneInfoDao.class).clone();
        zoneInfoDaoConfig.initIdentityScope(type);

        gridInfoDao = new GridInfoDao(gridInfoDaoConfig, this);
        zoneInfoDao = new ZoneInfoDao(zoneInfoDaoConfig, this);

        registerDao(GridInfo.class, gridInfoDao);
        registerDao(ZoneInfo.class, zoneInfoDao);
    }
    
    public void clear() {
        gridInfoDaoConfig.getIdentityScope().clear();
        zoneInfoDaoConfig.getIdentityScope().clear();
    }

    public GridInfoDao getGridInfoDao() {
        return gridInfoDao;
    }

    public ZoneInfoDao getZoneInfoDao() {
        return zoneInfoDao;
    }

}
