package fire_db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GRID_INFO".
 */
public class GridInfo {

    private long grid_id;
    private int grid_x;
    private int grid_y;
    private int grid_z;
    private int grid_type;
    private int grid_isfree;
    private double grid_temperature;
    private double grid_smoke;
    private double grid_O2;
    private double grid_CO;
    private double grid_CO2;
    private int grid_peoplenum;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GridInfo() {
    }

    public GridInfo(long grid_id) {
        this.grid_id = grid_id;
    }

    public GridInfo(long grid_id, int grid_x, int grid_y, int grid_z, int grid_type, int grid_isfree, double grid_temperature, double grid_smoke, double grid_O2, double grid_CO, double grid_CO2, int grid_peoplenum) {
        this.grid_id = grid_id;
        this.grid_x = grid_x;
        this.grid_y = grid_y;
        this.grid_z = grid_z;
        this.grid_type = grid_type;
        this.grid_isfree = grid_isfree;
        this.grid_temperature = grid_temperature;
        this.grid_smoke = grid_smoke;
        this.grid_O2 = grid_O2;
        this.grid_CO = grid_CO;
        this.grid_CO2 = grid_CO2;
        this.grid_peoplenum = grid_peoplenum;
    }

    public long getGrid_id() {
        return grid_id;
    }

    public void setGrid_id(long grid_id) {
        this.grid_id = grid_id;
    }

    public int getGrid_x() {
        return grid_x;
    }

    public void setGrid_x(int grid_x) {
        this.grid_x = grid_x;
    }

    public int getGrid_y() {
        return grid_y;
    }

    public void setGrid_y(int grid_y) {
        this.grid_y = grid_y;
    }

    public int getGrid_z() {
        return grid_z;
    }

    public void setGrid_z(int grid_z) {
        this.grid_z = grid_z;
    }

    public int getGrid_type() {
        return grid_type;
    }

    public void setGrid_type(int grid_type) {
        this.grid_type = grid_type;
    }

    public int getGrid_isfree() {
        return grid_isfree;
    }

    public void setGrid_isfree(int grid_isfree) {
        this.grid_isfree = grid_isfree;
    }

    public double getGrid_temperature() {
        return grid_temperature;
    }

    public void setGrid_temperature(double grid_temperature) {
        this.grid_temperature = grid_temperature;
    }

    public double getGrid_smoke() {
        return grid_smoke;
    }

    public void setGrid_smoke(double grid_smoke) {
        this.grid_smoke = grid_smoke;
    }

    public double getGrid_O2() {
        return grid_O2;
    }

    public void setGrid_O2(double grid_O2) {
        this.grid_O2 = grid_O2;
    }

    public double getGrid_CO() {
        return grid_CO;
    }

    public void setGrid_CO(double grid_CO) {
        this.grid_CO = grid_CO;
    }

    public double getGrid_CO2() {
        return grid_CO2;
    }

    public void setGrid_CO2(double grid_CO2) {
        this.grid_CO2 = grid_CO2;
    }

    public int getGrid_peoplenum() {
        return grid_peoplenum;
    }

    public void setGrid_peoplenum(int grid_peoplenum) {
        this.grid_peoplenum = grid_peoplenum;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
